apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shb-mobile-corp-service
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - service:email-service

